export const button_name = [
  { name: "Web" },
  { name: "Three.js" },
  { name: "Material UI" },
  { name: "Python" },
  { name: "Lua" },
  { name: "Java" },
  { name: "C++" },
  { name: "HTML" },
  { name: "C#" },
  { name: "JavaScript" },
  { name: "PHP" },
  { name: "Bootstrap UI" },
  { name: "React" },
  { name: "CSS" },
  { name: "Flutter" },
  { name: "Canvas" },
  { name: "SVG" },
  { name: "Laravel" },
  { name: "Unity" },
  { name: "Django" },
  { name: "R" },
  { name: "Vue" },
  { name: "Angular" },
  { name: "Pascal" },
  { name: "React Native" },
  { name: "Solidity" },
  { name: "Kotlin" },
  { name: "SwiftUI" },
  { name: "Typescript" },
  { name: "Dart" },
  { name: "GLSL" },
  { name: "Rust" },
  { name: "Swift" },
  { name: "Go" },
  { name: "Objective-C" },
  { name: "Svelte" },
  { name: "Lisp" },
  { name: "Ruby" },
  { name: "SASS" },
  { name: "Haskell" },
  { name: "Julia" },
  { name: "Perl" },
  { name: "Scala" },
  { name: "WGSL" },
  { name: "Erlang" },
  { name: "Elixir" },
];

export const display_buttons = [
  { name: "Web" },
  { name: "Three.js" },
  { name: "Material UI" },
  { name: "Python" },
  { name: "Lua" },
  { name: "Java" },
];
